###Create Profile
POST localhost:8080/api/v1/profile
Content-Type:application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "Ali123@gmail.com",
  "phone": "+998931234567",
  "password": "Ali123456",
  "role": "ROLE_MODERATOR"
}

###Update by Id
PUT  localhost:8080/api/v1/profile/9560c824-4773-4aa4-9f35-907e6d18ffd9
Content-Type: application/json

{
"name": "Jonibek",
"surname": "Choriyev",
  "email": "123@mazgi.ru",
  "password": "123456Jbk",
  "phone": "+998881475369"
}

###Update detail By Id
PUT localhost:8080/api/v1/profile/detail/9560c824-4773-4aa4-9f35-907e6d18ffd9
Content-Type: application/json

{
  "name": "Jonibekchik",
  "surname": "Choriyev"
}

###Paging
GET localhost:8080/api/v1/profile/page?page=1&size=5