###Create Profile
POST localhost:8081/api/v1/profile
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDM3ODM4MTMsImlkIjoxLCJyb2xlIjoiUk9MRV9NT0RFUkFUT1IiLCJleHAiOjE3MDM4NzAyMTQsImlzcyI6Imt1bl91eiB0ZXN0IHBvcnRhbGkifQ.RzvVTDDJecg4aqG1ADv-ceeP7EL0pd5Td1HlxQm12AuqVj6IUXUUmaHdwuLj5fhgIvVjHSn3CtbBNsCMqajuvg

//{
//  "name": "Vali",
//  "surname": "Valiyev",
//  "email": "",
//  "phone": "+998901234567",
//  "password": "Vali123456",
//  "role": "ROLE_MODERATOR"
//}
{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "Ali123@gmail.com",
  "phone": "+998932234567",
  "password": "Ali123456",
  "role": "ROLE_MODERATOR"
}

###Update by Id
PUT  localhost:8081/api/v1/profile/9560c824-4773-4aa4-9f35-907e6d18ffd9
Content-Type: application/json

{
"name": "Jonibek",
"surname": "Choriyev",
  "email": "123@mazgi.ru",
  "password": "123456Jbk",
  "phone": "+998881475369"
}

###Update detail By Id
PUT localhost:8081/api/v1/profile/detail/9560c824-4773-4aa4-9f35-907e6d18ffd9
Content-Type: application/json

{
  "name": "Jonibekchik",
  "surname": "Choriyev"
}

###Paging
GET localhost:8081/api/v1/profile/page?page=1&size=5

### Filter
POST localhost:8081/api/v1/profile/filter
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev"
}